matrix:
  include:
    - language: java
      jdk: openjdk8
      before_install:
      - cd coding && chmod +x mvnw
      script:
        - ./mvnw test
    
    - language: java
      jdk: openjdk8
      before_install:
      - cd gamification && chmod +x mvnw
      script:
        - ./mvnw test
    
    - language: node_js
      node_js:
        - "node"
      before_script:
        - cd web && npm install
      cache:
        directories:
          - "node_modules"
      script:
        - npm run test_headless
    
    - language: android
      dist: trusty
      android:
        components:
          - platform-tools
          - tools
          - extra-android-m2repository
          - sys-img-x86-android-28
        licenses:
          - 'android-sdk-preview-license-52d11cd2'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      before_install:
        - cd mobile && chmod +x gradlew
        - touch $HOME/.android/repositories.cfg
        - yes | sdkmanager "platforms;android-28"
        - yes | sdkmanager "build-tools;29.0.2"
      script:
        - ./gradlew build connectedCheck
notifications:
  email: false