matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd backend
      script:
        - ./mvnw test
    - language: node_js
      node_js:
        - "node"
      before_script:
        - cd frontend
        - npm install
      cache:
        directories:
          - "node_modules"
      script:
        - npm test_headless
        #update Protractor and selenium inluding chromeDriver
        #- npm webdriver-update
        #launch Selenium standalone in the background
        #- npm webdriver-start
        #run Protractor E2E tests
        #- npm e2e_headless
notifications:
  email: false