matrix:
  include:
    - language: java
      jdk: openjdk8
      before_install:
      - cd coding-quiz && chmod +x mvnw
      script:
        - ./mvnw test
    
    - language: java
      jdk: openjdk8
      before_install:
      - cd gamification && chmod +x mvnw
      script:
        - ./mvnw test
    
    - language: node_js
      node_js:
        - "node"
      before_script:
        - cd web && npm install
      cache:
        directories:
          - "node_modules"
      script:
        - npm run test_headless
notifications:
  email: false