matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_install:
      - cd backend && chmod +x mvnw
      script:
        - ./mvnw test
    - language: node_js
      node_js:
        - "node"
      before_script:
        - cd frontend && npm install
      cache:
        directories:
          - "node_modules"
      script:
        - npm run test_headless
        #update Protractor and selenium inluding chromeDriver
        #- npm run webdriver-update
        #launch Selenium standalone in the background
        #- npm run webdriver-start
        #run Protractor E2E tests
        #- npm run e2e_headless
notifications:
  email: false