zuul:
  debug:
    request: true
  sensitiveHeaders:
  prefix: /api
  routes:
    quizzes:
      path: /quizzes/**
      url: http://localhost:5000/quizzes
    results:
      path: /results/**
      url: http://localhost:5000/results
    leaders:
      path: /leaders/**
      url: http://localhost:5001/leaders
    stats:
      path: /stats/**
      url: http://localhost:5001/stats

okta:
  oauth2:
    issuer: https://dev-193618.oktapreview.com/oauth2/default
    clientId: 0oaqs9htbkKF1AOi00h7

logging:
  level:
    org.springframework.web: DEBUG